import { Inter } from "next/font/google";
import "./globals.css";
import "@fortawesome/fontawesome-free/css/all.css";
import AuthProvider from "@/Components/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dialable",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>

    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
    </AuthProvider>
  );
}
